Style/SymbolArray:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.6
# Want to be able to assign config
# without using =
Style/TrivialAccessors:
  Exclude:
    - 'lib/status_page/config.rb'

# Don't need to create frozen string const in specs
Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/**/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/MultilineMethodCallIndentation:
  Enabled: false

# allow "expect { \n ..}"
Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'
