name: Publish Ruby Gem

# Publish the gem to RubyGems when the git tag is pushed
on:
  push:
    tags: 'v*'
jobs:
  test:
    uses: ./.github/workflows/reusable-test.yml
  publish:
    name: Publish to RubyGems
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          echo "Running Successfully"
          gem build *.gemspec
          gem push *.gem
    env:
      GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
