name: Reusable Test Workflow

# This workflow runs when the branch is pushed/merged to master
# and when a PR is opened against master
on:
  workflow_call:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.6, 2.7, 3.0, 3.1, 3.2]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: bundle install
      name: Bundle
    - run: bundle exec rspec
      name: RSpec
